---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app-pod
  template:
    metadata:
      labels:
        app: python-app-pod
    spec:
      containers:
      - name: python-app
        image: sathviksp.azurecr.io/pythonapp:v1
        ports:
        - containerPort: 80

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
