FROM python:2.7-slim
WORKDIR /app
ADD . /app
RUN pip install --trusted-host pypi.python.org -r requirements.txt
RUN apt-get update && apt-get install -y iputils-ping curl && rm -rf /var/lib/apt/lists/* 
RUN ping -V && curl --version
EXPOSE 5010
CMD ["python", "app.py"]
