---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: python-app-dep
spec:
  type: LoadBalancer
  selector:
    app: python-app-pod
  ports:
    - name: python-app
      protocol: TCP
      port: 80
      targetPort: 5010
      nodePort: 30017

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis-dep
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379

